--- #YAML:1.0
name:                     WWW-Scraper-ISBN-LOC_Driver
version:                  0.24
abstract:                 Searches Library of Congress' online catalog for book information
author:
  - Andy Schamp <andy@schamp.net>
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                           5.006
  HTTP::Request::Common:          1.19
  LWP::UserAgent:                 2.00
  WWW::Scraper::ISBN::Driver:     0.15
recommends:
  Test::CPAN::Meta:               0
  Test::CPAN::Meta::JSON:         0
  Test::Pod:                      1.00
  Test::Pod::Coverage:            0.08
build_requires:
  IO::File:                       0
  Test::More:                     0.70

provides:
  WWW::Scraper::ISBN::LOC_Driver:
    file:     lib/WWW/Scraper/ISBN/LOC_Driver.pm
    version:  0.24

no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=WWW-Scraper-ISBN-LOC_Driver
  repository: http://github.com/barbie/www-scraper-isbn-loc_driver

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
